### ISSUE TITLE
Changes to makefile to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by erichmusick** [technopagan/mss-saliency#1]
I don't claim to be an expert in building in Linux, as I work in Windows all day, but I had to make a minor change to the makefile in order to build the SaliencyDetector on Ubuntu. Is this expected?

Line 48 should be:

```
g++ `Magick++-config --cppflags --cxxflags` -o"SaliencyDetector" $(OBJS) $(USER_OBJS) $(LIBS) `Magick++-config --ldflags --libs` 
```

I'm using ImageMagick 8:6.7.7.10-6ubuntu3

**Comment by technopagan** [comment]
Merged & fixed. Thank you so much for this! :)
